### ISSUE TITLE
[Feature] Handle colored output

### ISSUE THREAD

**Issue by jBouyoud** [robherley/go-test-action#7]
Probably pretty straightforward with a library like : https://www.npmjs.com/package/ansi-to-html

If you agree, I could try to open a pull request to handle this.

**Comment by robherley** [comment]
👋 @jBouyoud unfortunately the github markdown renderer does not support additional classes for colorizing text, so I opted to just scrub ansi entirely where possible:
- https://github.com/robherley/go-test-action/pull/19
